name: time
description: Type-safe DateTime and Duration calculations, powered by extensions.
version: 2.0.0
homepage: https://github.com/jogboms/time.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  test_coverage:
    git:
      url: https://github.com/jogboms/test-coverage.git
